sequenceDiagram
    User->>Lambda: Request
    Lambda->>DDB: Request
    DDB->>Aurora: Request
    Aurora->>S3: Request
    S3-->>Aurora: Response
    Aurora-->>DDB: Response
    DDB-->>Lambda: Response
    Lambda-->>User: Response